### ISSUE TITLE
add-source

### ISSUE THREAD

**Issue by fisx** [zalora/tinc#31]
When i `add-source` things manually before running `tinc`, `tinc` ignores the setup (obviously, as it move existing sandboxes out of the say).  Is there another way to add sources?

(This is really great otherwise.  Feels quite stable and mature, too.)

**Comment by sol** [comment]
Yes, we want this too.

Right now you can add a lidt of additional dependencies to `tincy.yaml`.  In addition you can override existing dependencies with a specific Git revision e.g.:

```yaml
#tincy.yaml 
dependencies:
 - name: some-sep
 - github: sol/some-dep
 - ref: some-commit-hash
```
(Note that this feature currently only works properly if you use Tinc in combination with a hpack `package.yaml`)

I'm inclined to extend this to allow local dependencies too.

**Comment by fisx** [comment]
That's helpful, thanks!  (-:

Could it be that #33 is closing this?  I don't see how it does, but I might be missing something..

**Comment by sol** [comment]
@fisx With the latest `master` you don't need a `package.yaml` anymore.

And yes, #33 addresses this, closing.

**Comment by sol** [comment]
Example usage:

```yaml
#tincy.yaml 
dependencies:
 - name: some-dep
   path: ../some-dep
```
